### ISSUE TITLE
Error: cannot launch node turtlebot_teleop from ck9_control_teleop.launch

### ISSUE THREAD

**Issue by lrs07** [centauri-robotics/ck9_gazebo#1]
On execution of `roslaunch ck9_simple_control ck9_control_teleop.launch` following error showed up:

```
ERROR: cannot launch node of type [turtlebot_teleop/turtlebot_teleop_key]: turtlebot_teleop
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/sudhansh/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share
**No processes to monitor**
```
I'm using Ubuntu 16.04 and ROS Kinetic. I've repeatedly followed the read-me and after execution of roslaunch line, the terminal waits for few seconds and then suspends. 
What could be the possible error?

**Comment by jash101** [comment]
Seems like you have not installed ros-kinetic-desktop-full, which led to some packages not being on your machine.
In this particular issue of yours, you do not have turtlebot_teleop package. So you just need to install it.
You can simply solve it with `sudo apt install ros-kinetic-turtlebot-teleop`
All dependencies can  be installed similarly.
