### ISSUE TITLE
catkin_make fails

### ISSUE THREAD

**Issue by DhruvaG2000** [centauri-robotics/ck9_gazebo#2]
after cloning when  I go back to ws and run catkin_make I get the following errors:

catkin_make
Base path: /home/dhruva/catkin_ws
Source space: /home/dhruva/catkin_ws/src
Build space: /home/dhruva/catkin_ws/build
Devel space: /home/dhruva/catkin_ws/devel
Install space: /home/dhruva/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/dhruva/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/dhruva/ros20_ws/devel;/home/dhruva/ws_moveit/devel;/opt/ros/kinetic
-- This workspace overlays: /home/dhruva/ros20_ws/devel;/home/dhruva/ws_moveit/devel;/opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /home/dhruva/.espressif/python_env/idf4.1_py2.7_env/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: False
-- catkin 0.7.20
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 6 packages in topological order:
-- ~~  - ck9_gazebo
-- ~~  - ck9_navigation
-- ~~  - ck9_simple_control
-- ~~  - realsense2_description
-- ~~  - sra
-- ~~  - realsense2_camera
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'ck9_gazebo'
-- ==> add_subdirectory(ck9_gazebo/ck9_gazebo)
-- +++ processing catkin package: 'ck9_navigation'
-- ==> add_subdirectory(ck9_gazebo/ck9_navigation)
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "move_base" with
  any of the following names:

    move_baseConfig.cmake
    move_base-config.cmake

  Add the installation prefix of "move_base" to CMAKE_PREFIX_PATH or set
  "move_base_DIR" to a directory containing one of the above files.  If
  "move_base" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ck9_gazebo/ck9_navigation/CMakeLists.txt:10 (find_package)

-- Could not find the required component 'move_base'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "move_base" with
  any of the following names:

    move_baseConfig.cmake
    move_base-config.cmake

  Add the installation prefix of "move_base" to CMAKE_PREFIX_PATH or set
  "move_base_DIR" to a directory containing one of the above files.  If
  "move_base" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ck9_gazebo/ck9_navigation/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/dhruva/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/dhruva/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

What can be done?

**Comment by DhruvaG2000** [comment]
Here is my ck9 tree inside src:
.
├── ck9_gazebo
│   ├── ck9_gazebo
│   │   ├── CMakeLists.txt
│   │   ├── launch
│   │   │   └── ck9_gazebo.launch
│   │   ├── meshes
│   │   │   ├── ck9.stl
│   │   │   ├── hokuyo.dae
│   │   │   ├── lidar.stl
│   │   │   └── wheel.stl
│   │   ├── package.xml
│   │   ├── rviz
│   │   │   └── ck9_gazebo.rviz
│   │   └── urdf
│   │       ├── ck9_gazebo.diff.plugins.xacro
│   │       ├── ck9_gazebo.plugins.xacro
│   │       └── ck9_gazebo.xacro
│   ├── ck9_navigation
│   │   ├── CMakeLists.txt
│   │   ├── launch
│   │   │   ├── amcl.launch
│   │   │   └── ck9_navigate.launch
│   │   ├── maps
│   │   │   ├── willowgarage_gmapping.pgm
│   │   │   └── willowgarage_gmapping.yaml
│   │   ├── package.xml
│   │   └── param
│   │       ├── base_local_planner_default_params.yaml
│   │       ├── costmap_common_params.yaml
│   │       ├── global_costmap_params.yaml
│   │       ├── local_costmap_params.yaml
│   │       └── move_base_params.yaml
│   ├── ck9_simple_control
│   │   ├── ck9_control_teleop.launch
│   │   ├── CMakeLists.txt
│   │   └── package.xml
│   └── README.md
├── CMakeLists.txt -> /opt/ros/kinetic/share/catkin/cmake/toplevel.cmake

**Comment by jash101** [comment]
Your system doesn't have move_base-config installed.
In your terminal, type:
`sudo apt install ros-kinetic-move-base-config`

**Comment by DhruvaG2000** [comment]
Thanks for the prompt response @jash101 !
A new issue I am now facing is the bot is not loading properly in Rviz  and the world isnt in gazebo..
I have posted the screenshots below:
![rviz_screenshot_2020_05_06-11_59_21](https://user-images.githubusercontent.com/41233856/81144238-46424700-8f91-11ea-9849-5a958a27ebbb.png)
![default_gzclient_camera(1)-2020-05-06T11_59_05 988222](https://user-images.githubusercontent.com/41233856/81144288-5b1eda80-8f91-11ea-9f62-129e30312a01.jpg)

**Comment by jash101** [comment]
The gazebo world has been intentionally kept empty. You can insert a model or launch a different world file as per your needs.
The rViz issue can be solved using following command: `sudo apt install ros-kinetic-joint-state-publisher-gui`

**Comment by DhruvaG2000** [comment]
RVIz issue still persists...
Also
![rviz_screenshot_2020_05_06-13_18_15](https://user-images.githubusercontent.com/41233856/81149604-26645080-8f9c-11ea-9c58-69f91d9ccbb5.png)
 I am not able to operate the bot with the given teleop...
output:
roslaunch ck9_simple_control ck9_control_teleop.launch 
... logging to /home/dhruva/.ros/log/a01f1a8e-8f6c-11ea-90fa-45752ef552d7/roslaunch-dhruva-Lenovo-G40-80-3105.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://dhruva-Lenovo-G40-80:46787/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /turtlebot_teleop_keyboard/scale_angular: 1.5
 * /turtlebot_teleop_keyboard/scale_linear: 0.5

NODES
  /
    turtlebot_teleop_keyboard (turtlebot_teleop/turtlebot_teleop_key)

ROS_MASTER_URI=http://localhost:11311

process[turtlebot_teleop_keyboard-1]: started with pid [3128]

Control Your Turtlebot!
---------------------------
Moving around:
   u    i    o
   j    k    l
   m    ,    .

q/z : increase/decrease max speeds by 10%
w/x : increase/decrease only linear speed by 10%
e/c : increase/decrease only angular speed by 10%
space key, k : force stop
anything else : stop smoothly

CTRL-C to quit

currently:	speed 0.2	turn 1 
currently:	speed 0.22	turn 1 
currently:	speed 0.242	turn 1 
currently:	speed 0.2662	turn 1 
currently:	speed 0.29282	turn 1 

The bot in gazebo simply doesnt respond to these commands..
However simple apply force works in gazebo so I know that gazebo is not lagging or anything..
Have I missed any step here?

**Comment by jash101** [comment]
Just to make sure, is this terminal active when you press the keys for teleop?

**Comment by DhruvaG2000** [comment]
here is the output of my other terminal:
roslaunch ck9_gazebo ck9_gazebo.launch 
... logging to /home/dhruva/.ros/log/a01f1a8e-8f6c-11ea-90fa-45752ef552d7/roslaunch-dhruva-Lenovo-G40-80-973.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://dhruva-Lenovo-G40-80:44427/

SUMMARY
========

PARAMETERS
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_gui: True
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/state_publisher)
    rviz (rviz/rviz)
    spawn_model (gazebo_ros/spawn_model)

ROS_MASTER_URI=http://localhost:11311

process[gazebo-1]: started with pid [994]
process[gazebo_gui-2]: started with pid [999]
process[joint_state_publisher-3]: started with pid [1004]
process[robot_state_publisher-4]: started with pid [1005]
process[spawn_model-5]: started with pid [1006]
process[rviz-6]: started with pid [1008]
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/joint_state_publisher/joint_state_publisher", line 6, in <module>
    from python_qt_binding.QtCore import pyqtSlot
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/__init__.py", line 55, in <module>
    from .binding_helper import loadUi, QT_BINDING, QT_BINDING_MODULES, QT_BINDING_VERSION  # @UnusedImport
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 271, in <module>
    getattr(sys, 'SELECT_QT_BINDING_ORDER', None),
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 117, in _select_qt_binding
    raise ImportError("Could not find Qt binding (looked for: %s):\n%s" % (', '.join(["'%s'" % b for b in binding_order]), '\n'.join(error_msgs)))
ImportError: Could not find Qt binding (looked for: 'pyqt', 'pyside'):
  ImportError for 'pyqt': No module named PyQt5.QtCore
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 108, in _select_qt_binding
    QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 150, in _load_pyqt
    _named_import('PyQt5.%s' % module_name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 130, in _named_import
    module = builtins.__import__(name)
ImportError: No module named PyQt5.QtCore

  ImportError for 'pyside': No module named PySide2.QtCore
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 108, in _select_qt_binding
    QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 182, in _load_pyside
    _named_import('PySide2.%s' % module_name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 130, in _named_import
    module = builtins.__import__(name)
ImportError: No module named PySide2.QtCore

Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[joint_state_publisher-3] process has died [pid 1004, exit code 1, cmd /opt/ros/kinetic/lib/joint_state_publisher/joint_state_publisher __name:=joint_state_publisher __log:=/home/dhruva/.ros/log/a01f1a8e-8f6c-11ea-90fa-45752ef552d7/joint_state_publisher-3.log].
log file: /home/dhruva/.ros/log/a01f1a8e-8f6c-11ea-90fa-45752ef552d7/joint_state_publisher-3*.log
[ INFO] [1588750913.360185247]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1588750913.364658068]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.0.107
[ INFO] [1588750913.613148541]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1588750913.614367751]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.0.107
SpawnModel script started
[ INFO] [1588750914.159616123, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/models.gazebosim.org"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/pr2_gripper"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/prius_hybrid"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/prius_hybrid_sensors"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/pulley_part"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/quadrotor"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/r2_description"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/radio_tower"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/ragdoll"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/reactor"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/region_event_box"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/robocup09_spl_field"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/robocup14_spl_field"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/robocup14_spl_goal"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/robocup_3Dsim_ball"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/robocup_3Dsim_field"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/robocup_3Dsim_goal"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/robocup_spl_ball"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/robonaut"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/round_tin_base"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/round_tin_top"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/salon"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/sand_island"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/saucepan"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/scanse_sweep"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/school"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/simple_arm"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/simple_arm_gripper"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/simple_gripper"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/sonoma_raceway"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/spectrum_plane"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/speed_limit_sign"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/src_doorway"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/standpipe"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/starting_pen"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/stereo_camera"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/stone_10_2_5_1cm"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/stop_light"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/stop_light_post"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/stop_sign"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/submarine"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/submarine_buoyant"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/submarine_sinking"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/t_brace_part"
[ INFO] [1588750914.261339985, 0.102000000]: Physics dynamic reconfigure ready.
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/table"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/table_marble"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/telephone_pole"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/textured_shapes"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/thrift_shop"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/tower_crane"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/trisphere_cycle"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/truss_bridge"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/tube_2_25cm"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/tube_9_5mm"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/turtlebot"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/u_joint_part"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/ur10"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/utility_cart"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/velodyne_hdl32"
[INFO] [1588750914.278213, 0.000000]: Loading model XML from ros parameter
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/vrc_driving_terrain"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/walkway_metal_45"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/walkway_metal_90"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/walkway_metal_straight"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/warehouse_robot"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/washer"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/water_tower"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/willowgarage"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/winding_valley_heightmap"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/wood_block_10_2_1cm"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home[INFO] [1588750914.292543, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
/dhruva/.gazebo/models/wood_cube_10cm"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/wood_cube_2_5cm"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/wood_cube_5cm"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/wood_cube_7_5cm"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/wooden_board"
[INFO] [1588750914.296967, 0.000000]: Calling service /gazebo/spawn_urdf_model
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/wooden_case"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "[ INFO] [1588750914.298067118, 0.137000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
/home/dhruva/.gazebo/models/wooden_case_metal_peg"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/wooden_case_wooden_peg"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/wooden_peg"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/wooden_peg_board"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/yosemite"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/youbot"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/dhruva/.gazebo/models/zephyr_delta_wing"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/opt/ros/kinetic/share/turtlebot3_gazebo/models/turtlebot3_autorace"
[INFO] [1588750915.110603, 0.242000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1588750915.133970713, 0.242000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1588750915.134057035, 0.242000000]: Starting Laser Plugin (ns = /)
[ INFO] [1588750915.136957137, 0.242000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1588750915.150887211, 0.242000000]: Physics dynamic reconfigure ready.
[ INFO] [1588750915.218703520, 0.242000000]: Starting plugin DiffDrive(ns = //)
[ WARN] [1588750915.218797945, 0.242000000]: DiffDrive(ns = //): missing <rosDebugLevel> default is na
[ INFO] [1588750915.219991010, 0.242000000]: DiffDrive(ns = //): <tf_prefix> = 
[ WARN] [1588750915.220164912, 0.242000000]: DiffDrive(ns = //): missing <publishWheelTF> default is false
[ WARN] [1588750915.220195767, 0.242000000]: DiffDrive(ns = //): missing <publishOdomTF> default is true
[ WARN] [1588750915.220225127, 0.242000000]: DiffDrive(ns = //): missing <publishWheelJointState> default is false
[ WARN] [1588750915.220348421, 0.242000000]: DiffDrive(ns = //): missing <wheelAcceleration> default is 0
[ WARN] [1588750915.220380948, 0.242000000]: DiffDrive(ns = //): missing <wheelTorque> default is 5
[ WARN] [1588750915.220482264, 0.242000000]: DiffDrive(ns = //): missing <odometrySource> default is 1
[ WARN] [1588750915.220567146, 0.242000000]: GazeboRosDiffDrive Plugin (ns = ) missing <publishTf>, defaults to 1
[ INFO] [1588750915.222053425, 0.242000000]: DiffDrive(ns = //): Try to subscribe to /cmd_vel
[ INFO] [1588750915.229164877, 0.242000000]: DiffDrive(ns = //): Subscribe to /cmd_vel
[ INFO] [1588750915.232702256, 0.242000000]: DiffDrive(ns = //): Advertise odom on /odom 
[spawn_model-5] process has finished cleanly
log file: /home/dhruva/.ros/log/a01f1a8e-8f6c-11ea-90fa-45752ef552d7/spawn_model-5*.log
static QPixmap QPixmap::grabWindow(WId, int, int, int, int) is deprecated, use QScreen::grabWindow() instead. Defaulting to primary screen.
static QPixmap QPixmap::grabWindow(WId, int, int, int, int) is deprecated, use QScreen::grabWindow() instead. Defaulting to primary screen.
[ERROR] [1588751295.344042024, 351.650000000]: poll failed with error Interrupted system call
[ERROR] [1588751295.377039173, 351.679000000]: poll failed with error Interrupted system call

(rviz:1008): Gtk-WARNING **: Theme file for default has no name


(rviz:1008): Gtk-WARNING **: Theme file for default has no directories

**Comment by DhruvaG2000** [comment]
> Just to make sure, is this terminal active when you press the keys for teleop?

yes
1. I run on one terminal the launch ck9 gazebo command
2. open new terminal source devel/setup bash and then run the teleop command from there

**Comment by jash101** [comment]
This is an unusual. To solve it faster, would you mind giving remote access?

**Comment by jash101** [comment]
Contact via https://wa.me/918850100529 for more info, and we'll help you out

**Comment by DhruvaG2000** [comment]
> Contact via https://wa.me/918850100529 for more info, and we'll help you out

okay

**Comment by DhruvaG2000** [comment]
Thanks for the help looks like the issue has been solved.
